apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: postgres-data
    namespace: trendgetter
  hostPath:
    path: /home/iksadnorth/project/trendgetter/postgres-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: airflow-dags
    namespace: trendgetter
  hostPath:
    path: /home/iksadnorth/project/trendgetter/dags
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-src-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: airflow-src
    namespace: trendgetter
  hostPath:
    path: /home/iksadnorth/project/trendgetter/src
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: airflow-logs
    namespace: trendgetter
  hostPath:
    path: /home/iksadnorth/project/trendgetter/logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-plugins-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: airflow-plugins
    namespace: trendgetter
  hostPath:
    path: /home/iksadnorth/project/trendgetter/plugins

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: mongodb-data
    namespace: trendgetter
  hostPath:
    path: /home/iksadnorth/project/trendgetter/mongodb-data

